### ISSUE TITLE
styled components and theme variable?

### ISSUE THREAD

**Issue by TAQ2** [TAQ2/hindi-practice#5]
/Users/arjun.gupta/Projects/hobby/learn-hindi/src/components/Alphabet/index.js

```
background-color: ${props => props.primary ? '#F7E3AF' : '#fff'};
```
does not work if the string is replaced with a variable

**Comment by mxstbr** [comment]
Is this an issue with `styled-components`? Do you have a reproduction somewhere by chance?

**Comment by TAQ2** [comment]
Hello Max, it is very inspiring that you are reaching out to find bugs! No this is not a bug with styled components, this issue was more of a note to self.

Now that I've got you here, got any tips on how to get people interested and contributing to a repo with no popularity?

**Comment by mxstbr** [comment]
>  got any tips on how to get people interested and contributing to a repo with no popularity?

Get it on the frontpage of HackerNews 😉 That's its own science, but if you can make that happen you'll get a lot of attention!

Good luck!
